server:
  port: 9401
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9400/eureka/
  instance:
    instance-id: ${spring.cloud.client.hostname}:${spring.application.name}:${spring.application.instance_id:${server.port}}

spring:
  profiles:
    active: native #配置中心加载方式
  application:
    name: config-server
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/dev/config/ #本地加载配置文件地址
