server:
  port: 9502

spring:
  application:
    name: config-client

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9500/eureka/
  instance:
    instance-id: ${spring.cloud.client.hostname}:${spring.application.name}:${spring.application.instance_id:${server.port}}

nickName: world + prod